[build]
  command = "npx prisma db push --schema prisma/schema.prisma && npx prisma generate --schema prisma/schema.prisma && astro build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
